/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ferna
 */
public class MenuUsu extends javax.swing.JFrame {
    private int IdUsu;
    public MenuUsu() {
        initComponents();
        c = new ControllerPesquisa(this);
    }
    public MenuUsu(int IdUsu) {
        this.IdUsu = IdUsu;
        initComponents();
        c = new ControllerPesquisa(this);
    }

    public JTextField getTestId() {
        return TestId;
    }

    public void setTestId(JTextField TestId) {
        this.TestId = TestId;
    }
    

    public int getIdUsu() {
        return IdUsu;
    }

    public void setIdUsu(int IdUsu) {
        this.IdUsu = IdUsu;
    }

    public JTabbedPane getjTabbedPane2() {
        return jTabbedPane2;
    }

    public void setjTabbedPane2(JTabbedPane jTabbedPane2) {
        this.jTabbedPane2 = jTabbedPane2;
    }

    public JTabbedPane getjTabbedPane3() {
        return jTabbedPane3;
    }

    public void setjTabbedPane3(JTabbedPane jTabbedPane3) {
        this.jTabbedPane3 = jTabbedPane3;
    }

    public JTabbedPane getjTabbedPane4() {
        return jTabbedPane4;
    }

    public void setjTabbedPane4(JTabbedPane jTabbedPane4) {
        this.jTabbedPane4 = jTabbedPane4;
    }

    public JTabbedPane getjTabbedPane5() {
        return jTabbedPane5;
    }

    public void setjTabbedPane5(JTabbedPane jTabbedPane5) {
        this.jTabbedPane5 = jTabbedPane5;
    }

    public JTabbedPane getjTabbedPane6() {
        return jTabbedPane6;
    }

    public void setjTabbedPane6(JTabbedPane jTabbedPane6) {
        this.jTabbedPane6 = jTabbedPane6;
    }
    

    public JTextField getBuscaMus() {
        return BuscaMus;
    }

    public void setBuscaMus(JTextField BuscaMus) {
        this.BuscaMus = BuscaMus;
    }

    public JButton getBuscarMusica() {
        return BuscarMusica;
    }

    public void setBuscarMusica(JButton BuscarMusica) {
        this.BuscarMusica = BuscarMusica;
    }

    public JTextArea getResultadoMusica() {
        return ResultadoMusica;
    }

    public void setResultadoMusica(JTextArea ResultadoMusica) {
        this.ResultadoMusica = ResultadoMusica;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public ControllerPesquisa getC() {
        return c;
    }

    public void setC(ControllerPesquisa c) {
        this.c = c;
    }

    public JButton getAntMu() {
        return AntMu;
    }

    public void setAntMu(JButton AntMu) {
        this.AntMu = AntMu;
    }

    public JButton getCurMu() {
        return CurMu;
    }

    public void setCurMu(JButton CurMu) {
        this.CurMu = CurMu;
    }

    public JButton getDescuMu() {
        return DescuMu;
    }

    public void setDescuMu(JButton DescuMu) {
        this.DescuMu = DescuMu;
    }

    public JTextArea getMusicaAtu() {
        return MusicaAtu;
    }

    public void setMusicaAtu(JTextArea MusicaAtu) {
        this.MusicaAtu = MusicaAtu;
    }

    public JButton getProxMu() {
        return ProxMu;
    }

    public void setProxMu(JButton ProxMu) {
        this.ProxMu = ProxMu;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BuscaMus = new javax.swing.JTextField();
        BuscarMusica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadoMusica = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        MusicaAtu = new javax.swing.JTextArea();
        AntMu = new javax.swing.JButton();
        ProxMu = new javax.swing.JButton();
        CurMu = new javax.swing.JButton();
        DescuMu = new javax.swing.JButton();
        TestId = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscaMus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BuscaMus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaMusActionPerformed(evt);
            }
        });

        BuscarMusica.setText("BUSCAR");
        BuscarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMusicaActionPerformed(evt);
            }
        });

        ResultadoMusica.setColumns(20);
        ResultadoMusica.setRows(5);
        jScrollPane1.setViewportView(ResultadoMusica);

        MusicaAtu.setColumns(20);
        MusicaAtu.setRows(5);
        jScrollPane2.setViewportView(MusicaAtu);

        AntMu.setText("Anterior");
        AntMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntMuActionPerformed(evt);
            }
        });

        ProxMu.setText("Próxima");
        ProxMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProxMuActionPerformed(evt);
            }
        });

        CurMu.setText("Curtir");
        CurMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurMuActionPerformed(evt);
            }
        });

        DescuMu.setText("Descurtir");
        DescuMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescuMuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CurMu)
                    .addComponent(DescuMu))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AntMu)
                    .addComponent(ProxMu))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BuscaMus)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BuscarMusica)
                        .addGap(18, 18, 18)
                        .addComponent(TestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BuscaMus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarMusica)
                    .addComponent(TestId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProxMu)
                        .addGap(18, 18, 18)
                        .addComponent(AntMu)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CurMu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DescuMu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Pesquisa", jPanel1);

        jTabbedPane2.addTab("Criar", jTabbedPane3);
        jTabbedPane2.addTab("Excluir", jTabbedPane4);
        jTabbedPane2.addTab("Editar", jTabbedPane5);
        jTabbedPane2.addTab("Musicas", jTabbedPane6);

        jTabbedPane1.addTab("Playlists", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaMusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaMusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaMusActionPerformed

    private void BuscarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMusicaActionPerformed
    String x = getBuscaMus().getText();
    getTestId().setText(String.valueOf(IdUsu));
    c.mostrarTodasMusicas(x);
    c.exibirMusicaAtual();
    }//GEN-LAST:event_BuscarMusicaActionPerformed

    private void ProxMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProxMuActionPerformed
    c.proximaMusica();
    }//GEN-LAST:event_ProxMuActionPerformed

    private void AntMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntMuActionPerformed
    c.musicaAnterior();
    }//GEN-LAST:event_AntMuActionPerformed

    private void CurMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurMuActionPerformed

    try{
    c.curtirMusica();
    }catch(SQLException e){
     System.err.println(e);
    }
    }//GEN-LAST:event_CurMuActionPerformed

    private void DescuMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuMuActionPerformed
    try{
    c.descurtirMusica();
    }catch(SQLException e){
     System.err.println(e);
    }
    }//GEN-LAST:event_DescuMuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsu().setVisible(true);
            }
        });
    }
private ControllerPesquisa c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AntMu;
    private javax.swing.JTextField BuscaMus;
    private javax.swing.JButton BuscarMusica;
    private javax.swing.JButton CurMu;
    private javax.swing.JButton DescuMu;
    private javax.swing.JTextArea MusicaAtu;
    private javax.swing.JButton ProxMu;
    private javax.swing.JTextArea ResultadoMusica;
    private javax.swing.JTextField TestId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    // End of variables declaration//GEN-END:variables
}
